# Generated by Django 4.2.24 on 2026-03-22 22:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAIResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_response', models.JSONField()),
                ('attempt_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'db_table': 'temporary_ai_response',
                'indexes': [models.Index(fields=['candidate', 'created_at'], name='temporary_a_candida_970c2c_idx'), models.Index(fields=['expires_at'], name='temporary_a_expires_233b0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('cv_screening', 'CV Screening'), ('interview_analysis', 'Interview Analysis')], db_index=True, max_length=20)),
                ('fit_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('summary', models.TextField()),
                ('strengths', models.JSONField()),
                ('weaknesses', models.JSONField()),
                ('feedback', models.TextField()),
                ('recommendation', models.CharField(blank=True, choices=[('hire', 'Hire'), ('hold', 'Hold'), ('reject', 'Reject')], max_length=20, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.interview')),
            ],
            options={
                'db_table': 'ai_report',
                'indexes': [models.Index(fields=['candidate', 'report_type'], name='ai_report_candida_71709e_idx'), models.Index(fields=['candidate', 'interview'], name='ai_report_candida_8c7906_idx'), models.Index(fields=['report_type', 'created_at'], name='ai_report_report__71ca57_idx')],
            },
        ),
    ]
