# Generated by Django 4.2.24 on 2026-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='extracted_skills',
            field=models.JSONField(default=list),
        ),
    ]
