# Generated by Django 4.2.24 on 2026-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_reports", "0002_add_extracted_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="skills_match_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
