# Generated by Django 4.2.24 on 2026-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reports', '0003_aireport_skills_match_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='aireport',
            name='education_match',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
