# Generated by Django 4.2.24 on 2026-03-23 12:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('video_submitted', 'Video Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected_cv', 'Rejected CV'), ('rejected_interview', 'Rejected Interview'), ('hold', 'Hold')], db_index=True, default='applied', max_length=50)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cv_file', models.CharField(blank=True, max_length=500, null=True)),
                ('cv_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('cv_text', models.TextField(blank=True, null=True)),
                ('cv_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('cv_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('error', 'Error')], db_index=True, default='uploaded', max_length=20)),
                ('video_intro_url', models.CharField(blank=True, max_length=500, null=True)),
                ('video_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('video_attempts', models.IntegerField(default=0)),
                ('ai_score', models.IntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_strengths', models.JSONField(default=list)),
                ('ai_weaknesses', models.JSONField(default=list)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('account_created', 'Account Created'), ('application_submitted', 'Application Submitted'), ('cv_uploaded', 'CV Uploaded'), ('ai_analysis_complete', 'AI Analysis Complete'), ('shortlisted', 'Shortlisted'), ('rejected_cv', 'Rejected CV'), ('video_uploaded', 'Video Uploaded'), ('interview_scheduled', 'Interview Scheduled'), ('interview_confirmed', 'Interview Confirmed'), ('interview_completed', 'Interview Completed'), ('interview_report_generated', 'Interview Report Generated'), ('offered', 'Offered'), ('rejected_interview', 'Rejected Interview'), ('hold', 'Hold')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter'), ('both', 'Both')], default='both', max_length=20)),
                ('created_by_type', models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter'), ('system', 'System')], max_length=20, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job', 'status', 'ai_score'], name='candidate_job_id_a040fa_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job', 'applied_at'], name='candidate_job_id_9311c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'job')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['candidate', 'timestamp'], name='activity_lo_candida_e0056f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['event_type', 'timestamp'], name='activity_lo_event_t_fe184c_idx'),
        ),
    ]
