# Generated by Django 4.2.24 on 2026-03-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_cv_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_temp_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_temp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
