# Generated by Django 4.2.24 on 2026-03-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_cv_temp_key_candidate_video_temp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv_temp_key',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='video_temp_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='video_last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='video_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
