# Generated by Django 4.2.24 on 2026-03-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_remove_candidate_cv_temp_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_skills',
            field=models.JSONField(default=list),
        ),
    ]
