# Generated by Django 4.2.24 on 2026-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_add_ai_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('video_submitted', 'Video Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected_cv', 'Rejected CV'), ('rejected_interview', 'Rejected Interview'), ('hold', 'Hold')], db_index=True, default='applied', max_length=50),
        ),
    ]
