# Generated by Django 4.2.24 on 2026-05-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('application_submitted', 'Application Submitted'), ('cv_uploaded', 'CV Uploaded'), ('ai_analysis_queued', 'AI Analysis Queued'), ('ai_analysis_complete', 'AI Analysis Complete'), ('shortlisted', 'Shortlisted'), ('rejected_cv', 'Rejected CV'), ('video_uploaded', 'Video Uploaded'), ('interview_scheduled', 'Interview Scheduled'), ('interview_confirmed', 'Interview Confirmed'), ('interview_completed', 'Interview Completed'), ('interview_report_generated', 'Interview Report Generated'), ('offered', 'Offered'), ('rejected_interview', 'Rejected Interview'), ('hold', 'Hold')], db_index=True, max_length=50),
        ),
    ]
