# Generated by Django 4.2.24 on 2026-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_activitylog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('application_submitted', 'Application Submitted'), ('cv_uploaded', 'CV Uploaded'), ('ai_analysis_queued', 'AI Analysis Queued'), ('ai_analysis_complete', 'AI Analysis Complete'), ('shortlisted', 'Shortlisted'), ('rejected_cv', 'Rejected CV'), ('withdrawn', 'Withdrawn'), ('video_uploaded', 'Video Uploaded'), ('interview_scheduled', 'Interview Scheduled'), ('interview_confirmed', 'Interview Confirmed'), ('interview_completed', 'Interview Completed'), ('interview_report_generated', 'Interview Report Generated'), ('offered', 'Offered'), ('rejected_interview', 'Rejected Interview'), ('hold', 'Hold')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('video_submitted', 'Video Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected_cv', 'Rejected CV'), ('withdrawn', 'Withdrawn'), ('rejected_interview', 'Rejected Interview'), ('hold', 'Hold')], db_index=True, default='applied', max_length=50),
        ),
    ]
