# Generated by Django 4.2.24 on 2026-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_activitylog_event_type_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('video_submitted', 'Video Submitted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected_cv', 'Rejected CV'), ('withdrawn', 'Withdrawn'), ('rejected_interview', 'Rejected Interview'), ('hold', 'Hold')], db_index=True, default='draft', max_length=50),
        ),
    ]
