# Generated by Django 4.2.24 on 2026-03-22 22:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('recruiter', 'Recruiter'), ('admin', 'Admin')], default='recruiter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recruiter_user',
                'indexes': [models.Index(fields=['email'], name='recruiter_u_email_f69486_idx'), models.Index(fields=['is_active'], name='recruiter_u_is_acti_33760d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandidateUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidate_user',
                'indexes': [models.Index(fields=['email'], name='candidate_u_email_f14371_idx')],
            },
        ),
    ]
