# Generated by Django 4.2.24 on 2026-05-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_candidateuser_location_recruiteruser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiteruser',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
