# Generated by Django 6.0.4 on 2026-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_systemmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetric',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='systemmetric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='systemmetric',
            index=models.Index(fields=['key', '-updated_at'], name='users_syste_key_c8d244_idx'),
        ),
    ]
