# Generated by Django 6.0.4 on 2026-05-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_systemmetric_key_alter_systemmetric_updated_at_and_more'),
        ('users', '0003_recruiteruser_profile_photo'),
    ]

    operations = [
    ]
