# Generated by Django 4.2.24 on 2026-05-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_systemmetric_key_alter_systemmetric_updated_at_and_more'),
        ('users', '0003_recruiteruser_profile_photo'),
    ]

    operations = [
    ]
