# Generated by Django 6.0.6 on 2026-06-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260530_1910'),
        ('users', '0004_merge_20260531_1131'),
    ]

    operations = [
    ]
