# Generated by Django 4.2.24 on 2026-03-22 22:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('department', models.CharField(choices=[('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('food_beverage', 'Food & Beverage'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night'), ('rotating', 'Rotating')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('seasonal', 'Seasonal')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.recruiteruser')),
            ],
            options={
                'db_table': 'job',
                'indexes': [models.Index(fields=['is_active'], name='job_is_acti_65cfb7_idx'), models.Index(fields=['department', 'is_active'], name='job_departm_1df5f2_idx')],
            },
        ),
    ]
