# Generated by Django 4.2.24 on 2026-03-25 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('title', 'location', 'department')},
        ),
    ]
