# Generated by Django 4.2.24 on 2026-05-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='core_skills',
            field=models.JSONField(blank=True, default=list, help_text="List of required skills for this job, e.g. ['customer service', 'communication']"),
        ),
    ]
