# Generated by Django 4.2.24 on 2026-05-06 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_is_acti_65cfb7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='job',
            name='openings_count',
            field=models.IntegerField(default=1, help_text='Number of positions available for this job', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham')], default='ETB', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('yearly', 'Per Year')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('front_office', 'Front Office / Reception'), ('concierge', 'Concierge'), ('guest_relations', 'Guest Relations'), ('housekeeping', 'Housekeeping'), ('laundry', 'Laundry'), ('food_beverage', 'Food & Beverage'), ('restaurant', 'Restaurant'), ('bar_lounge', 'Bar / Lounge'), ('room_service', 'Room Service'), ('banquet_events', 'Banquet & Events'), ('kitchen', 'Kitchen'), ('executive_chef', 'Executive Chef'), ('sous_chef', 'Sous Chef'), ('line_cook', 'Line Cook'), ('maintenance', 'Maintenance / Engineering'), ('security', 'Security'), ('safety', 'Health & Safety'), ('management', 'Management'), ('general_manager', 'General Manager'), ('department_manager', 'Department Manager'), ('human_resources', 'Human Resources'), ('finance_accounting', 'Finance & Accounting'), ('sales_marketing', 'Sales & Marketing'), ('procurement', 'Procurement / Purchasing'), ('spa_wellness', 'Spa & Wellness'), ('fitness_center', 'Fitness Center'), ('recreation', 'Recreation / Activities'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('seasonal', 'Seasonal'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning (6:00 AM - 2:00 PM)'), ('afternoon', 'Afternoon (2:00 PM - 10:00 PM)'), ('evening', 'Evening (4:00 PM - 12:00 AM)'), ('night', 'Night (10:00 PM - 6:00 AM)'), ('rotating', 'Rotating Shifts'), ('flexible', 'Flexible Hours'), ('on_call', 'On-Call'), ('split', 'Split Shift')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'deleted_at'], name='job_is_acti_575ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type', 'is_active'], name='job_employm_783d33_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location', 'is_active'], name='job_locatio_a6d7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'is_active'], name='job_title_131559_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='job_created_010237_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_by', 'is_active'], name='job_posted__cc1512_idx'),
        ),
    ]
