# Generated by Django 4.2.24 on 2026-05-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_core_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='openings_count',
            field=models.IntegerField(default=1, help_text='Number of positions available for this job'),
        ),
    ]
