# Generated by Django 4.2.24 on 2026-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_salary_currency_job_salary_max_job_salary_min_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='job_is_acti_65cfb7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='job',
            name='core_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills for this job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('front_office', 'Front Office / Reception'), ('concierge', 'Concierge'), ('guest_relations', 'Guest Relations'), ('bell_staff', 'Bell Staff / Porter'), ('housekeeping', 'Housekeeping'), ('laundry', 'Laundry'), ('linen_room', 'Linen Room'), ('public_area', 'Public Area Cleaning'), ('food_beverage', 'Food & Beverage (General)'), ('restaurant', 'Restaurant'), ('bar_lounge', 'Bar / Lounge'), ('room_service', 'Room Service'), ('banquet_events', 'Banquet & Events'), ('breakfast_room', 'Breakfast Room'), ('vip_lounge', 'VIP Lounge'), ('kitchen', 'Kitchen (General)'), ('executive_chef', 'Executive Chef'), ('sous_chef', 'Sous Chef'), ('line_cook', 'Line Cook'), ('pastry', 'Pastry / Bakery'), ('cold_kitchen', 'Cold Kitchen / Garde Manger'), ('stewarding', 'Stewarding / Dishwashing'), ('maintenance', 'Maintenance / Engineering'), ('security', 'Security'), ('safety', 'Health & Safety'), ('loss_prevention', 'Loss Prevention'), ('management', 'Management (General)'), ('general_manager', 'General Manager'), ('department_manager', 'Department Manager'), ('assistant_manager', 'Assistant Manager'), ('front_office_manager', 'Front Office Manager'), ('executive_housekeeper', 'Executive Housekeeper'), ('f_b_manager', 'Food & Beverage Manager'), ('human_resources', 'Human Resources'), ('finance_accounting', 'Finance & Accounting'), ('sales_marketing', 'Sales & Marketing'), ('procurement', 'Procurement / Purchasing'), ('it_support', 'IT Support'), ('admin_office', 'Administrative Office'), ('spa_wellness', 'Spa & Wellness'), ('fitness_center', 'Fitness Center / Gym'), ('recreation', 'Recreation / Activities'), ('swimming_pool', 'Swimming Pool'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('seasonal', 'Seasonal'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month'), ('yearly', 'Per Year')], default='monthly', help_text='Period for salary', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='shift_type',
            field=models.CharField(choices=[('morning', 'Morning (6:00 AM - 2:00 PM)'), ('afternoon', 'Afternoon (2:00 PM - 10:00 PM)'), ('evening', 'Evening (4:00 PM - 12:00 AM)'), ('night', 'Night (10:00 PM - 6:00 AM)'), ('rotating', 'Rotating Shifts'), ('flexible', 'Flexible Hours'), ('on_call', 'On-Call'), ('split', 'Split Shift')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'deleted_at'], name='job_is_acti_575ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employment_type', 'is_active'], name='job_employm_783d33_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location', 'is_active'], name='job_locatio_a6d7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'is_active'], name='job_title_131559_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='job_created_010237_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_by', 'is_active'], name='job_posted__cc1512_idx'),
        ),
    ]
