# Generated by Django 6.0.4 on 2026-05-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_job_options_remove_job_job_is_acti_65cfb7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last date candidates can apply. Leave blank for open-ended roles.', null=True),
        ),
    ]
