# Generated by Django 4.2.24 on 2026-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_application_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(choices=[('none', 'No formal education required'), ('high_school', 'High School / Secondary'), ('vocational', 'Vocational / Trade Certificate'), ('diploma', 'Diploma (Hospitality / Hotel Management)'), ('bachelor', "Bachelor's Degree (Hospitality / Business)"), ('master', "Master's Degree (MBA / Hospitality Management)"), ('professional_cert', 'Professional Certification (e.g., CHA, CHT)')], db_index=True, default='none', help_text='Minimum education level required for this job', max_length=20),
        ),
    ]
