# Generated by Django 4.2.24 on 2026-06-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_extra_fields'),
        ('job', '0008_job_education_level'),
    ]

    operations = [
    ]
