# Generated by Django 4.2.24 on 2026-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_merge_0003_job_extra_fields_0008_job_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='core_skills',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills for this job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='openings_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of positions available for this job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=[('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham')], default='ETB', help_text='Currency code for salary', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary for this position', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary for this position', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Period for salary', max_length=20),
        ),
    ]
