# Generated by Django 4.2.24 on 2026-03-23 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('job', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('stage', models.CharField(choices=[('stage_1', 'Stage 1'), ('stage_2', 'Stage 2'), ('stage_3', 'Stage 3')], default='stage_1', max_length=20)),
                ('meet_link', models.CharField(max_length=500)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=20)),
                ('bot_join_status', models.CharField(choices=[('pending', 'Pending'), ('joined', 'Joined'), ('failed', 'Failed'), ('not_enabled', 'Not Enabled')], default='pending', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.recruiteruser')),
            ],
            options={
                'db_table': 'interview',
            },
        ),
        migrations.CreateModel(
            name='InterviewConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interview')),
            ],
            options={
                'db_table': 'interview_conversation',
                'indexes': [models.Index(fields=['interview', 'timestamp'], name='interview_c_intervi_dbd4de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_time'], name='interview_status_149231_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['candidate', 'status'], name='interview_candida_ca09e2_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['recruiter', 'scheduled_time'], name='interview_recruit_934d4a_idx'),
        ),
    ]
